services:
  db:
    image: ponugotikavya/pyapp:dbimage
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  auth_service:
    image: ponugotikavya/pyapp:authimage
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - mynetwork

  book_service:
    image: ponugotikavya/pyapp:bookimage
    ports:
      - "5002:5002"
    depends_on:
      - db
    networks:
      - mynetwork

  borrow_service:
    image: ponugotikavya/pyapp:borrowimage
    ports:
      - "5003:5003"
    depends_on:
      - db
    networks:
      - mynetwork

  app_service:
    image: ponugotikavya/pyapp:frontend
    ports:
      - "5000:5000"
    depends_on:
      - auth_service
      - book_service
      - borrow_service
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
